import { ArrowRight } from "lucide-react";

const workflow = [
  ["Upload the reference", "Choose a JPEG, PNG or WebP up to 4 MB. Cloudinary stores the selected file. A resized sample is its own reference; it is not a verified answer key.", "Upload API / Node.js SDK"],
  ["Set the question", "Choose text, counts or custom questions. Define what to include. For receipts, extract the total without supplying the expected answer in the prompt.", "Task builder / JSON Schema"],
  ["Measure the baseline", "Run the same question on the original three times. A field is stable when all three valid answers agree. If none are stable, the test stops. Partial stability allows a sweep with limited coverage.", "AI Vision General / Analyze API"],
  ["Test smaller versions", "Test eligible widths of 1200, 800, 600, 400 and 200px. Each uses automatic quality and receives three analyses with the same task. Source aspect ratio and format are retained.", "c_limit,w_<width>/q_auto"],
  ["Review the evidence", "Compare stable fields, inspect the returned answers and review excluded fields. Only a complete pass produces a recommendation. The smallest passing width is not necessarily the smallest file.", "InvariantLens comparison rules"],
  ["Export the report", "Save the task, responses and decisions as JSON before refreshing. A full sweep uses up to 18 analyses. Stop prevents later requests; accepted provider requests may still complete.", "JSON report export"],
];
const results = [
  ["PASS", "All selected original fields are stable and preserved in every variant run.", "Consider this tested width for the same task."],
  ["PARTIAL", "Comparable fields match, but some original fields could not be compared.", "Resolve excluded fields before using a full-task recommendation."],
  ["DRIFT", "A stable answer changes in at least one variant run.", "Inspect the values and image; retain a passing version or the original."],
  ["UNSTABLE", "Original answers or reported original model versions differ.", "Clarify the task and start a new experiment. Preserve the old report."],
  ["ERROR", "A run failed, was invalid, had incompatible model information, or had no stable fields.", "Inspect the run log and provider configuration."],
  ["NOT TESTED", "No measurement exists for this width.", "Do not infer a result."],
];

export function HowItWorks({ onStart }: { onStart: () => void }) {
  return <article className="product-guide">
    <header className="pg-header"><div><p className="pg-kicker">PRODUCT GUIDE</p><h1>How InvariantLens works</h1><p>Measure whether image optimization changes the answers your application needs.</p></div><button className="pg-start" onClick={onStart}>Start a test <ArrowRight size={16}/></button></header>
    <div className="pg-layout"><nav className="pg-nav" aria-label="Guide contents"><span>ON THIS PAGE</span><a href="#pg-process">Test workflow</a><a href="#pg-results">Results and decisions</a><a href="#pg-help">Unstable answers</a><a href="#pg-samples">Validation images</a><a href="#pg-tools">Cloudinary integration</a><a href="#pg-limits">Scope and limits</a></nav><div className="pg-body">
      <section id="pg-process"><h2>Test workflow</h2><p>One reference image. One unchanged task. Three observations at each tested size.</p><ol className="pg-workflow">{workflow.map(([name, description, tool], i) => <li key={name}><span className="pg-step">{i+1}</span><div><h3>{name}</h3><p>{description}</p><small>{tool}</small></div></li>)}</ol></section>
      <section id="pg-results"><h2>Results and decisions</h2><div className="pg-table-wrap"><table><caption>How to interpret a measurement</caption><thead><tr><th scope="col">Result</th><th scope="col">Meaning</th><th scope="col">Next step</th></tr></thead><tbody>{results.map(([name, meaning, action]) => <tr key={name}><th scope="row"><span className={`pg-label pg-${name.toLowerCase().replace(' ','-')}`}>{name}</span></th><td>{meaning}</td><td>{action}</td></tr>)}</tbody></table></div><p className="pg-note">Matching answers establish repeatability. Check them against the image or a reviewed answer before treating them as correct.</p></section>
      <section id="pg-help"><h2>When original answers vary</h2><p>A result such as <code>pens: 3 / 2 / 2</code> occurs before smaller images are evaluated. It cannot establish damage from resizing.</p><details open><summary>Make the category explicit</summary><p>A highlighter may be counted as a pen. Try “Count ballpoint pens; exclude markers and highlighters.” For traffic scenes, distinguish bicycles from motorcycles and state whether background objects count.</p></details><details><summary>Check image clarity and scope</summary><p>Review occlusion, reflections and small text. If you crop the image or change the question, start a new experiment and preserve the earlier report.</p></details><details><summary>Keep disagreement in the evidence</summary><p>Do not replace disagreement with a majority vote or repeat until answers agree. Use human review or a task-specific detector when the model cannot reliably resolve a detail.</p></details></section>
      <section id="pg-samples"><h2>Validation images</h2><p>The receipt collection contains 10 internet-sourced candidates with licenses, attribution and source hashes. A demonstrated drift case needs a stable, nonempty original baseline and a changed answer at a smaller tested width.</p><p>The screening script runs three original analyses, then three each at 600px and 200px for eligible stable images. Reports retain passing, unstable and failed cases. The workspace offers the full width sweep.</p><p>See the screening observations below for the latest complete experiment, including request failures and unstable originals. Receipt comparisons normalize monetary formatting. A recommendation requires a manually checked total and currency.</p><div className="pg-links"><a href="/validation/results.json" target="_blank" rel="noreferrer">Screening observations ↗</a><a href="/validation/ATTRIBUTION.md" target="_blank" rel="noreferrer">Sources and licenses ↗</a><a href="/validation/manifest.json" target="_blank" rel="noreferrer">Image manifest ↗</a></div><p className="pg-note">Selecting examples that show drift demonstrates a failure mode. It does not estimate how often the problem occurs in production.</p></section>
      <section id="pg-tools"><h2>Cloudinary integration</h2><dl className="pg-tools"><div><dt>Upload API + Node.js SDK</dt><dd>Server-side upload and versioned HTTPS delivery URLs. Credentials remain on the server.<a href="https://cloudinary.com/documentation/image_upload_api_reference" target="_blank" rel="noreferrer">Upload reference ↗</a></dd></div><div><dt>Image transformations</dt><dd><code>c_limit,w_600/q_auto</code> limits width and applies automatic quality. Size and quality change together in this experiment.<a href="https://cloudinary.com/documentation/image_optimization" target="_blank" rel="noreferrer">Optimization guide ↗</a></dd></div><div><dt>AI Vision General</dt><dd>The Analyze API receives a URL and prompt with a JSON Schema. The server polls asynchronous tasks and validates responses before comparison.<a href="https://cloudinary.com/documentation/analyze_api_guide" target="_blank" rel="noreferrer">Analyze API guide ↗</a></dd></div></dl></section>
      <section id="pg-limits"><h2>Scope and limits</h2><ul className="pg-limits"><li>Recommendations cover this image, task and tested settings. They do not certify accuracy or safety.</li><li>Unknown provider model versions cannot be independently verified. Structured JSON does not prevent incorrect answers.</li><li>Reports remain in browser memory until exported. Assets remain in the configured Cloudinary account; delivery URLs are accessible to anyone with the link.</li><li>Recorded examples contain unverified historical observations. Live tests make real API calls and consume provider usage.</li><li>Comparisons measure output consistency and tested width. Transformed file size and production failure rates are not measured.</li></ul></section>
      <footer className="pg-footer"><span>InvariantLens · Product documentation</span><button onClick={onStart}>Open workspace <ArrowRight size={14}/></button></footer>
    </div></div>
  </article>;
}
